name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Install frontend dependencies
      run: npm ci --prefix frontend

    - name: Lint frontend
      run: npm run lint --prefix frontend

    - name: Build frontend
      run: npm run build --prefix frontend

    - name: Install Playwright
      run: |
        cd frontend
        npx playwright install --with-deps

    - name: Run Playwright tests
      run: |
        cd frontend
        npx playwright test