name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install root dependencies
      run: npm install
    - name: Install frontend dependencies
      run: npm install --prefix frontend
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps --prefix frontend
    - name: Create .env file
      run: echo "MONGO_DB_URI=mongodb://mongodb:27017/test" > .env
    - name: Start backend server
      run: npm start &
    - name: Wait for backend server
      run: npx wait-on http://localhost:5000
    - name: Run Playwright tests
      run: npx playwright test --prefix frontend
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: frontend/playwright-report/
        retention-days: 30
